// Real browser + local FastAPI fixture. Start tests/preview_server.py first.
import { createRequire } from 'node:module'
import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import assert from 'node:assert/strict'
const root = fileURLToPath(new URL('..', import.meta.url))
const work = path.resolve(root, '../.work')
const require = createRequire(path.join(root, 'frontend/package.json'))
const { chromium } = require('playwright')
const port = (await readFile(path.join(work, 'preview-port.txt'), 'utf8')).trim()
const base = `http://127.0.0.1:${port}`
const output = path.join(root, 'docs/previews')
await mkdir(output, { recursive: true })
const edge = 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'
const browser = await chromium.launch({ headless: true, ...(existsSync(edge) ? { executablePath: edge } : {}) })
const context = await browser.newContext({ viewport: { width: 1440, height: 1080 }, reducedMotion: 'reduce' })
const page = await context.newPage()
const errors = []
const apiErrors = []
page.on('pageerror', error => errors.push(error.message))
page.on('response', async response => { if (response.url().endsWith('/studio/action') && response.status() >= 400) apiErrors.push({action: response.request().postDataJSON()?.action, status: response.status(), message: (await response.json()).message}) })
page.on('dialog', dialog => dialog.accept())
const steps = []
function done(step) { steps.push(step); console.log('PASS:', step) }
async function ready() {
  await page.waitForFunction(() => { const img=document.querySelector('.ma-canvas>img'); return img?.naturalWidth>0 && !document.querySelector('.ma-render-pill') }, { timeout: 30000 })
}
try {
  await page.goto(base)
  await page.getByRole('heading', { name: '可编辑画布预览' }).waitFor()
  await ready()
  await page.screenshot({ path: path.join(output, 'studio-desktop.png'), fullPage: true })
  done('Desktop canvas renders real backend PNG')
  await page.getByRole('button', { name: /光幕/ }).click()
  await page.getByLabel('主标题', { exact: true }).fill('我的 4K 私人影院')
  await ready()
  assert.equal(await page.getByRole('button', { name: /光幕/ }).getAttribute('aria-pressed'), 'true')
  await page.getByRole('button', { name: '编辑画布布局', exact: true }).click()
  const titleHandle = page.getByRole('button', { name: '移动标题，支持方向键', exact: true })
  await titleHandle.focus()
  await page.keyboard.press('ArrowRight')
  await page.getByRole('button', { name: '布局与配色', exact: true }).click()
  assert.equal(await page.getByRole('slider', { name: '标题横向位置', exact: true }).inputValue(), '8')
  done('Preset selection, title edit and keyboard canvas positioning')
  await page.getByRole('button', { name: '编辑画布布局', exact: true }).click()
  await page.getByRole('button', { name: '添加方案', exact: true }).click()
  await page.getByLabel('方案名称', { exact: true }).fill('浏览器验证方案')
  await page.getByRole('button', { name: '保存为我的方案', exact: true }).click()
  await page.getByRole('button', { name: '浏览器验证方案', exact: true }).waitFor()
  await page.getByRole('button', { name: /应用封面方案|保存方案设置/ }).click()
  await page.getByRole('status').filter({ hasText: '当前虚拟库封面已更新' }).waitFor()
  done('Save custom preset and apply settings to current virtual library')
  const exportWait = page.waitForEvent('download')
  await page.getByRole('button', { name: '分享方案', exact: true }).click()
  const presetDownload = await exportWait
  const presetPath = path.join(work, 'browser-preset.json')
  await presetDownload.saveAs(presetPath)
  assert.equal(JSON.parse(await readFile(presetPath, 'utf8')).format, 'mediaarchiver-preset-v1')
  await page.locator('input[type=file]').nth(0).setInputFiles(presetPath)
  await page.getByRole('status').filter({ hasText: '方案已导入' }).waitFor()
  done('Export and reimport a real preset JSON file')
  await page.getByRole('button', { name: '生成当前封面', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '已开始生成' }).waitFor()
  await page.waitForFunction(() => document.querySelector('.ma-job') === null)
  await page.getByRole('button', { name: /历史封面/ }).first().click()
  await page.locator('.ma-history-card').first().waitFor({ timeout: 30000 })
  await page.screenshot({ path: path.join(output, 'studio-history.png'), fullPage: true })
  await page.getByRole('button', { name: '查看与下载', exact: true }).first().click()
  await page.getByRole('dialog', { name: '历史封面预览' }).waitFor()
  const imageWait = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载原图', exact: true }).click()
  const imageDownload = await imageWait
  assert.ok(/\.(png|gif)$/.test(imageDownload.suggestedFilename()))
  await page.getByRole('button', { name: '恢复此方案', exact: true }).last().click()
  await page.getByRole('heading', { name: '可编辑画布预览', exact: true }).waitFor()
  done('Background generation, history preview, download and restore')
  await page.getByRole('button', { name: '打开配置', exact: true }).click()
  await page.getByRole('heading', { name: '运行与定时', exact: true }).waitFor()
  await page.screenshot({ path: path.join(output, 'studio-config.png'), fullPage: true })
  const backupWait = page.waitForEvent('download')
  await page.getByRole('button', { name: '立即备份', exact: true }).click()
  const backupDownload = await backupWait
  const backupPath = path.join(work, 'browser-backup.json')
  await backupDownload.saveAs(backupPath)
  assert.equal(JSON.parse(await readFile(backupPath, 'utf8')).format, 'mediaarchiver-config-v1')
  await page.locator('input[type=file]').nth(1).setInputFiles(backupPath)
  await page.getByRole('status').filter({ hasText: '备份已载入表单' }).waitFor()
  await page.getByRole('button', { name: '清理图片缓存', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '图片缓存已清理' }).waitFor()
  await page.getByRole('button', { name: '清理字体缓存', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '字体缓存已清理' }).waitFor()
  done('Configuration backup/import and both cache actions')
  const testFont = existsSync(path.join(work, 'test-font.ttf')) ? path.join(work, 'test-font.ttf') : path.join(root, 'plugins.v2/mediaarchiver/fonts/NotoSansSC.ttf')
  {
    await page.locator('input[type=file]').nth(2).setInputFiles(testFont)
    await page.getByRole('status').filter({ hasText: '字体已加入字体库' }).waitFor({ timeout: 30000 })
    done('Font file upload through browser FileReader and actual API')
  }
  await page.getByRole('button', { name: /默认标题与字体/ }).click()
  await page.getByLabel('默认副标题', { exact: true }).fill('MY CINEMA')
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await page.getByRole('heading', { name: '可编辑画布预览', exact: true }).waitFor()
  done('Configuration save event reloads host plugin state')
  await page.setViewportSize({ width: 390, height: 844 })
  await ready()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile page must not overflow horizontally')
  assert.ok(await page.getByRole('button', { name: '生成当前封面', exact: true }).isVisible(), 'Mobile generation action remains available')
  await page.screenshot({ path: path.join(output, 'studio-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '打开配置', exact: true }).click()
  await page.getByRole('heading', { name: '运行与定时', exact: true }).waitFor()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile config must not overflow horizontally')
  await page.screenshot({ path: path.join(output, 'studio-config-mobile.png'), fullPage: true })
  done('390px mobile canvas and configuration without horizontal overflow')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(base+'/federation')
  await page.waitForFunction(() => window.__federationReady === true)
  await page.getByRole('heading', { name: '可编辑画布预览', exact: true }).waitFor()
  await ready()
  assert.ok(await page.evaluate(() => getComputedStyle(document.querySelector('.ma-studio')).backgroundColor === 'rgb(11, 17, 21)'), 'Federation must load CSS from MoviePilot-like resource path')
  done('Production federation Page loads shared Vue and hashed CSS/JS through host path')
  await page.getByRole('button', { name: '刷新媒体库', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '已读取 2 个原生媒体库' }).waitFor()
  const nativeCard = page.locator('[data-library-key^="native:"]').first()
  const nativeKey = await nativeCard.getAttribute('data-library-key')
  await nativeCard.locator('.ma-library-editor').click()
  await ready()
  await page.getByRole('checkbox', { name: '动态封面', exact: true }).uncheck()
  await ready()
  await page.screenshot({ path: path.join(output, 'studio-native.png'), fullPage: true })
  done('Native libraries discovered by distinct IDs and real artwork previewed')
  await page.getByRole('button', { name: '生成并更新原生库封面', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '已开始生成' }).waitFor()
  await page.waitForFunction(() => document.querySelector('.ma-job') === null)
  await page.getByRole('status').filter({ hasText: '原生封面更新完成：0 GIF，1 静态，0 失败' }).waitFor()
  done('Native publish performs real base64 image POST to the isolated Emby fixture')
  await page.getByRole('button', { name: /历史封面/ }).first().click()
  const beforeCard = page.locator('.ma-history-card').filter({ hasText: '更新前备份' }).first()
  await beforeCard.waitFor()
  await page.screenshot({ path: path.join(output, 'studio-native-history.png'), fullPage: true })
  await beforeCard.getByRole('button', { name: '查看与下载', exact: true }).click()
  await page.getByRole('button', { name: '恢复原生库图片', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '原生库图片已恢复' }).waitFor()
  done('Native pre-update image backup can be restored from the real history dialog')
  await page.getByRole('button', { name: '封面生成', exact: true }).click()
  await page.getByLabel('Emby 服务器', { exact: true }).waitFor()
  assert.equal(await page.getByLabel('Emby 服务器', { exact: true }).locator('option').count(), 1)
  assert.equal(await page.locator('.ma-library-card').count(), 6)
  await page.getByRole('button', { name: '预览已选库', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.ma-library-art img').length === 6 && [...document.querySelectorAll('.ma-library-art img')].every(i => i.naturalWidth > 0), { timeout: 30000 })
  await page.screenshot({ path: path.join(output, 'studio-server.png'), fullPage: true })
  done('One server selector and six library cards each show a real preview')
  await page.getByRole('button', { name: '生成并应用已选库', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '已开始逐库生成' }).waitFor()
  await page.getByRole('status').filter({ hasText: /服务器封面完成：\d+ GIF，\d+ 静态，0 失败/ }).first().waitFor({ timeout: 40000 })
  const batchResponse = await page.request.get(base+'/api/v1/plugin/MediaArchiver/studio', { headers: { Authorization: 'Bearer local-test' } })
  const batch = (await batchResponse.json()).data.job
  assert.equal(batch.animated + batch.static, 6)
  assert.equal(batch.results.filter(row => row.native && row.status === 'published').length, 2)
  assert.equal(batch.results.filter(row => !row.native && row.status === 'generated').length, 4)
  done('Whole-server batch publishes two native covers and generates four virtual covers')
  await page.setViewportSize({ width: 390, height: 844 })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  assert.ok(await page.getByRole('button', { name: '生成并应用已选库', exact: true }).isVisible())
  await page.screenshot({ path: path.join(output, 'studio-server-mobile.png'), fullPage: true })
  done('Whole-server cards and primary batch action remain usable at 390px')
  await page.locator('[data-library-key="attribute:remux"] .ma-library-editor').click()
  await page.getByRole('checkbox', { name: '动态封面', exact: true }).check()
  await ready()
  await page.getByRole('button', {name:'播放动图预览',exact:true}).click()
  await ready()
  assert.ok((await page.locator('.ma-canvas>img').getAttribute('src')).startsWith('data:image/gif;'))
  await page.getByRole('button', {name:'暂停动图预览',exact:true}).click()
  await ready()
  assert.ok((await page.locator('.ma-canvas>img').getAttribute('src')).startsWith('data:image/png;'))
  done('Real multi-poster GIF preview starts and pauses back to a static image')
  assert.deepEqual(errors, [], 'No uncaught browser errors')
  assert.deepEqual(apiErrors, [], 'No failed studio actions during the browser workflow')
  await writeFile(path.join(work, 'ui-test-results.json'), JSON.stringify({ steps, errors, apiErrors, browser: await browser.version() }, null, 2))
  console.log(`ALL ${steps.length} BROWSER SCENARIOS PASSED`)
} catch (error) {
  await page.screenshot({ path: path.join(work, 'ui-failure.png'), fullPage: true })
  await writeFile(path.join(work, 'ui-failure.txt'), await page.locator('body').innerText())
  console.error('Browser errors:', errors)
  throw error
} finally { await browser.close() }
